spring.datasource.url=jdbc:mariadb://db:3306/cake_db
spring.datasource.username=cake_user
spring.datasource.password=cake_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
